### ISSUE TITLE
Handsaw::Filters::IndentedParagraphの変数の初期化のバグ

### ISSUE THREAD

**Issue by ryotaro-uchigane** [PORT-INC/handsaw#4]
Handsaw::Filters::IndentedParagraphを継承したfilterを使用する時、
直近で定義した属性を引き継いでしまう

例えば、IndentedParagraphを継承したimage_filterを作った場合、下記のパターンだと出力時、ふたつのimage要素がtext: あああああという情報をもってしまう。
```
image:
  path: https://hogehoge.jp/imgs/b204e9800998ecf8427e.png
  text: あああああ

image:
  path: https://hogehoge.jp/imgs/bslkjfalksjlksajlkfje.png

```

以下のようにIndentedParagraph.rbのcallメソッド内で変数を初期化するようにしたい。
問題なさそうだったらプルリクあげます。
```
      def call
        variables = instance_variables
        doc.search('div').each do |div|
          @type = div.attributes['class']&.value
          next unless @type == element_type
          values = []
          div.children.each do |item|
            if item.attributes['class']&.value == 'option'
              define_variable item
              item.replace ''
            elsif item.text != "\n"
              values << item.to_s
            end
          end
          @value = values.join.gsub(/^\s*$/, '')
          div.replace Nokogiri::HTML.fragment(CGI.unescapeHTML(compile))
          (instance_variables - variables).each { |v| remove_instance_variable v } # こっちに持っていきたい
        end
        
       (instance_variables - variables).each { |v| remove_instance_variable v } # こいつ
        doc
      end
```
